import React from 'react';
import {
  Activity,
  Add,
  Api,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  Blog,
  ChartLine,
  Chat,
  ChevronLeft,
  ChevronRight,
  Close,
  CloudUpload,
  Copy,
  Dashboard as DashboardIcon,
  Debug,
  Document,
  DragVertical,
  Earth,
  Edit,
  Email,
  Error as ErrorIcon,
  Events,
  Globe,
  Image,
  Information,
  Integration,
  Launch,
  List,
  Menu,
  OpenPanelLeft,
  OverflowMenuVertical,
  Portfolio,
  Quotes,
  Renew,
  Save,
  Search,
  Settings as SettingsIcon,
  SidePanelClose,
  SidePanelOpen,
  CheckmarkFilled,
  CheckmarkOutline,
  WarningAlt,
  WarningFilled,
  Purchase,
  Locked,
  Upload,
  User,
  UserAvatar,
  View,
  ViewOff,
} from '@carbon/icons-react';

/* ── Carbon Icon registry ── */
export const iconRegistry = {
  Activity,
  Add,
  Api,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Blog,
  Chat,
  CheckmarkFilled,
  CheckmarkOutline,
  ChevronRight,
  Close,
  CloudUpload,
  Dashboard: DashboardIcon,
  Document,
  Earth,
  Email,
  Error: ErrorIcon,
  Events,
  Globe,
  Image,
  Information,
  Integration,
  Launch,
  List,
  OpenPanelLeft,
  OverflowMenuVertical,
  Plug,
  Portfolio,
  Quotes,
  Save,
  Search,
  Settings: SettingsIcon,
  SidePanelClose,
  SidePanelOpen,
  Upload,
  User,
  UserAvatar,
  WarningAlt,
  WarningFilled,
};

export function CarbonIcon({ name, size = 20, ...props }) {
  const Component = iconRegistry[name];
  if (!Component) return null;
  return <Component size={size} {...props} />;
}

/* ── Default icon map for built-in nav items ── */
export const defaultIconMap = {
  api: 'Api',
  comments: 'Chat',
  dashboard: 'Dashboard',
  domains: 'Earth',
  docs: 'Document',
  connectors: 'Plug',
  integrations: 'Integration',
  logs: 'Activity',
  post: 'Blog',
  pages: 'Document',
  media: 'Image',
  site: 'Globe',
  users: 'User',
};

export function getNavIcon(item) {
  if (item.icon && iconRegistry[item.icon]) return <CarbonIcon name={item.icon} size={20} />;
  const mapped = defaultIconMap[item.id];
  if (mapped) return <CarbonIcon name={mapped} size={20} />;
  if (item.kind === 'collection') return <CarbonIcon name="List" size={20} />;
  if (item.kind === 'singleton') return <CarbonIcon name="Settings" size={20} />;
  return <CarbonIcon name="Document" size={20} />;
}

// Re-export individual icons used directly by components
export {
  Activity,
  Add,
  Api,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  Blog,
  ChartLine,
  Chat,
  ChevronLeft,
  ChevronRight,
  Close,
  Copy,
  DashboardIcon,
  Debug,
  Document,
  DragVertical,
  Earth,
  Edit,
  Email,
  Events,
  Globe,
  Image,
  Integration,
  Launch,
  List,
  Menu,
  OpenPanelLeft,
  OverflowMenuVertical,
  Portfolio,
  Quotes,
  Renew,
  Search,
  SettingsIcon,
  SidePanelClose,
  SidePanelOpen,
  CheckmarkFilled,
  WarningAlt,
  Purchase,
  Locked,
  Upload,
  User,
  UserAvatar,
  View,
  ViewOff,
};
